defmodule ProblemTest do
  use ExUnit.Case
  doctest Problem1
  doctest Problem2
  doctest Problem3
  doctest Problem4
  doctest Problem5
  doctest Problem6
  doctest Problem7
  doctest Problem8
  doctest Problem9
  doctest Problem10
  doctest Problem11
  doctest Problem12
  doctest Problem13
  doctest Problem14
  doctest Problem15
  doctest Problem16
  doctest Problem17
  doctest Problem18
  doctest Problem19
  doctest Problem20
  doctest Problem21
  doctest Problem22
  doctest Problem23
  doctest Problem24
  doctest Problem25
  doctest Problem28
end
